<?php
/* $Id$ */

/**
 * @file
 * Very simple DRUPAL module
 */

/**
 * Implementation of hook_menu().
 */
function modulo_prueba_menu($may_cache) {
  $items = array();

  $items['helloworld'] = array(
    'title' => 'Hello World',
    'access callback' => TRUE,
    'page callback' => 'modulo_prueba_hello_world_page',
    'type' => MENU_NORMAL_ITEM,
    'menu' => 'navigation',
  );

  return $items;
}


/**
 * Function which generate page
 */
function modulo_prueba_hello_world_page() {
  return '<p>Hello world!</p>';
}